FROM public.ecr.aws/lambda/python:3.12

# Set working directory to the Lambda task root so the handler is importable
WORKDIR /var/task

RUN pip install uv
#COPY src/common_utils.py .
#COPY src/config.py .
#COPY src/data_utils.py .
#COPY src/plot_utils.py .
#COPY src/train_utils.py .
COPY src/lambda_function.py .
COPY src/stage1-E1-FINAL-model.onnx .

#RUN apt-get update && apt-get install -y libgl1 libglib2.0-0
RUN uv pip install --target /var/task numpy pydantic pillow
#RUN uv pip install --target /var/task torch torchvision --index-url https://download.pytorch.org/whl/cpu
RUN uv pip install --target /var/task onnx onnxruntime

EXPOSE 8080

CMD ["lambda_function.lambda_handler"]